lexer grammar LALexer;

ALGORITMO: 'algoritmo';
FIM_ALGORITMO: 'fim_algoritmo';
DECLARE: 'declare';
LITERAL: 'literal';
INTEIRO: 'inteiro';
REAL: 'real';
LOGICO: 'logico';
LEIA: 'leia';
ESCREVA: 'escreva';
SE: 'se';
ENTAO: 'entao';
SENAO: 'senao';
FIM_SE: 'fim_se';
CASO: 'caso';
SEJA: 'seja';
FIM_CASO: 'fim_caso';
PARA: 'para';
ATE: 'ate';
FACA: 'faca';
FIM_PARA: 'fim_para';
ENQUANTO: 'enquanto';
FIM_ENQUANTO: 'fim_enquanto';
REGISTRO: 'registro';
FIM_REGISTRO: 'fim_registro';
TIPO: 'tipo';
PROCEDIMENTO: 'procedimento';
FIM_PROCEDIMENTO: 'fim_procedimento';
FUNCAO: 'funcao';
FIM_FUNCAO: 'fim_funcao';
VAR: 'var';
CONSTANTE: 'constante';
RETORNE: 'retorne';
NAO: 'nao';
E: 'e';
OU: 'ou';
VERDADEIRO: 'verdadeiro';
FALSO: 'falso';

IDENT: [a-zA-Z_] [a-zA-Z_0-9]*;
NUM_REAL: [0-9]+ '.' [0-9]+;
NUM_INT: [0-9]+;
CADEIA: '"' ~["\r\n]* '"';

ABRE_PAR: '(';
FECHA_PAR: ')';
ABRE_COL: '[';
FECHA_COL: ']';
VIRGULA: ',';
DOIS_PONTOS: ':';
ATRIBUICAO: '<-';
MENOR_IGUAL: '<=';
MAIOR_IGUAL: '>=';
DIFERENTE: '<>';
INTERVALO: '..';
PONTO: '.';
MENOR: '<';
MAIOR: '>';
IGUAL: '=';
SOMA: '+';
SUB: '-';
MULT: '*';
DIV: '/';
MOD: '%';
CIRCUNFLEXO: '^';
E_COMERCIAL: '&';

COMENTARIO: '{' ~[}\r\n]* '}' -> skip;
ESPACO: [ \t\r\n]+ -> skip;

ERRO_COMENTARIO: '{' ~[}\r\n]* ('\r'? '\n' | EOF);
ERRO_CADEIA: '"' ~["\r\n]* ('\r'? '\n' | EOF);
ERRO_SIMBOLO: .;
